qcacld-3.0: Avoid undefined references when WLAN_POWER_DEBUG is disabled
Ensure these functions are declared irrespective of WLAN_POWER_DEBUG,
in order to satisfy the following link-time warnings:

drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_main.o: in function `hdd_wlan_start_modules':
wlan_hdd_main.c:(.text+0x34dc): undefined reference to `hdd_sysfs_create_driver_root_obj'

drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_main.o: in function `hdd_wlan_stop_modules':
wlan_hdd_main.c:(.text+0x914c): undefined reference to `hdd_sysfs_destroy_driver_root_obj'

Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>